
/* TABELA: Naves */
CREATE TABLE NAVE(
	NAVE_SQ_NAVE int NOT NULL,
	NAVE_NM_NAVE varchar(100) NOT NULL,
	NAVE_TX_MODELO varchar(150) NOT NULL,
	NAVE_NR_PASSAGEIROS int NOT NULL,
	NAVE_TX_VARGA float,
	NAVE_TX_CLASSE varchar(100) NOT NULL
	
)
GO

ALTER TABLE NAVE ADD CONSTRAINT PK_NAVE PRIMARY KEY (NAVE_SQ_NAVE);
GO


/* TABELA: PLANETAS */
CREATE TABLE PLANETA(
	PLAN_SQ_PLANETA int NOT NULL,
	PLAN_NM_PLANETA varchar(50) NOT NULL,
	PLAN_VL_ROTACAO float NOT NULL,
	PLAN_VL_ORBITA float NOT NULL,
	PLAN_VL_DIAMETRO float NOT NULL,
	PLAN_TX_CLIMA varchar(50) NOT NULL,
	PLAN_NR_POPULACAO int NOT NULL
)
GO

ALTER TABLE PLANETA ADD CONSTRAINT PK_PLANETA PRIMARY KEY (PLAN_SQ_PLANETA);


/* TABELA: PILOTOS */
CREATE TABLE PILOTO(
	PILO_SQ_PILOTO int NOT NULL,
	PILO_NM_PILOTO varchar(200) NOT NULL,
	PILO_DT_NASCIMENTO varchar(10) NOT NULL,
	PLAN_SQ_PLANETA int NOT NULL
)
GO

ALTER TABLE PILOTO ADD CONSTRAINT PK_PILOTO PRIMARY KEY(PILO_SQ_PILOTO);
GO

ALTER TABLE PILOTO ADD CONSTRAINT FK_PILOTO_PLANETA FOREIGN KEY (PLAN_SQ_PLANETA)
REFERENCES PLANETA (PLAN_SQ_PLANETA);
GO


/* TABELA: PILOTOS NAVES */
CREATE TABLE PILOTO_NAVE(
	PILO_SQ_PILOTO int NOT NULL
	NAVE_SQ_NAVE int NOT NULL,
	PINA_IN_AUTORIZADO bit NOT NULL DEFAULT 1
)
GO

ALTER TABLE PILOTO_NAVE ADD CONSTRAINT PK_PILOTO_NAVE PRIMARY KEY (PILO_SQ_PILOTO, NAVE_SQ_NAVE);
GO

ALTER TABLE PILOTO_NAVE ADD CONSTRAINT FK_PILOTO_NAVE_PILOTO FOREIGN KEY (PILO_SQ_PILOTO)
REFERENCES PILOTO (PILO_SQ_PILOTO);
GO

ALTER TABLE PILOTO_NAVE ADD CONSTRAINT FK_PILOTO_NAVE_NAVE FOREIGN KEY (NAVE_SQ_NAVE)
REFERENCES NAVE (NAVE_SQ_NAVE);
GO


/* TABELA: HISTORICO VIAGENS */
CREATE TABLE HISTORICO_VIAGEM(
	NAVE_SQ_NAVE int NOT NULL,
	PILO_SQ_PILOTO int NOT NULL,
	HIVI_DT_SAIDA datetime NOT NULL,
	HIVI_DT_CHEGADA datetime NOT NULL
)
GO

ALTER TABLE HISTORICO_VIAGEM ADD CONSTRAINT FK_HISTORICO_VIAGEM_PILOTO_NAVE (PILO_SQ_PILOTO, NAVE_SQ_NAVE)
REFERENCES PILOTO_NAVE (PILO_SQ_PILOTO, NAVE_SQ_NAVE);
GO

ALTER TABLE HISTORICO_VIAGEM CHECK CONSTRAINT FK_HISTORICO_VIAGEM_PILOTO_NAVE 